var searchData=
[
  ['aboutactivity',['AboutActivity',['../classunicopa_1_1copa_1_1app_1_1gui_1_1AboutActivity.html',1,'unicopa::copa::app::gui']]],
  ['abstractrequest',['AbstractRequest',['../classunicopa_1_1copa_1_1base_1_1com_1_1request_1_1AbstractRequest.html',1,'unicopa::copa::base::com::request']]],
  ['abstractresponse',['AbstractResponse',['../classunicopa_1_1copa_1_1base_1_1com_1_1request_1_1AbstractResponse.html',1,'unicopa::copa::base::com::request']]],
  ['addchildnode',['addChildNode',['../classunicopa_1_1copa_1_1base_1_1event_1_1CategoryNodeImpl.html#a9a5475f29659e41d6c4ca7385d4ea427',1,'unicopa::copa::base::event::CategoryNodeImpl']]],
  ['addgcmkey',['addGCMKey',['../classunicopa_1_1copa_1_1base_1_1UserSettings.html#a9712503dcc767a735082b80286aa7522',1,'unicopa::copa::base::UserSettings']]],
  ['addroletouserrequest',['AddRoleToUserRequest',['../classunicopa_1_1copa_1_1base_1_1com_1_1request_1_1AddRoleToUserRequest.html',1,'unicopa::copa::base::com::request']]],
  ['addroletouserrequest',['AddRoleToUserRequest',['../classunicopa_1_1copa_1_1base_1_1com_1_1request_1_1AddRoleToUserRequest.html#a22a6a770935cae5c8d0f4cd9a54cff42',1,'unicopa::copa::base::com::request::AddRoleToUserRequest']]],
  ['addroletouserresponse',['AddRoleToUserResponse',['../classunicopa_1_1copa_1_1base_1_1com_1_1request_1_1AddRoleToUserResponse.html',1,'unicopa::copa::base::com::request']]],
  ['addsingleeventrequest',['AddSingleEventRequest',['../classunicopa_1_1copa_1_1base_1_1com_1_1request_1_1AddSingleEventRequest.html',1,'unicopa::copa::base::com::request']]],
  ['addsingleeventrequest',['AddSingleEventRequest',['../classunicopa_1_1copa_1_1base_1_1com_1_1request_1_1AddSingleEventRequest.html#a84265afab2a444a83956f4400bdcb2d1',1,'unicopa::copa::base::com::request::AddSingleEventRequest']]],
  ['addsingleeventresponse',['AddSingleEventResponse',['../classunicopa_1_1copa_1_1base_1_1com_1_1request_1_1AddSingleEventResponse.html',1,'unicopa::copa::base::com::request']]],
  ['addsingleeventupdaterequest',['AddSingleEventUpdateRequest',['../classunicopa_1_1copa_1_1base_1_1com_1_1request_1_1AddSingleEventUpdateRequest.html',1,'unicopa::copa::base::com::request']]],
  ['addsingleeventupdaterequest',['AddSingleEventUpdateRequest',['../classunicopa_1_1copa_1_1base_1_1com_1_1request_1_1AddSingleEventUpdateRequest.html#aa491b495fa7514a88c5f76fa030d50ad',1,'unicopa::copa::base::com::request::AddSingleEventUpdateRequest']]],
  ['addsingleeventupdateresponse',['AddSingleEventUpdateResponse',['../classunicopa_1_1copa_1_1base_1_1com_1_1request_1_1AddSingleEventUpdateResponse.html',1,'unicopa::copa::base::com::request']]],
  ['addsubscription',['addSubscription',['../classunicopa_1_1copa_1_1base_1_1UserSettings.html#a507def45a855e2a9e32bcb33eff8e10b',1,'unicopa::copa::base::UserSettings']]],
  ['alert',['alert',['../classunicopa_1_1copa_1_1app_1_1gui_1_1PopUp.html#a776dc3e0e868d681fcec702086de8f7f',1,'unicopa::copa::app::gui::PopUp']]],
  ['apiexception',['APIException',['../classunicopa_1_1copa_1_1base_1_1com_1_1exception_1_1APIException.html',1,'unicopa::copa::base::com::exception']]],
  ['apiexceptiondeserializer',['APIExceptionDeserializer',['../classunicopa_1_1copa_1_1base_1_1com_1_1serialization_1_1APIExceptionDeserializer.html',1,'unicopa::copa::base::com::serialization']]]
];
